#!/usr/bin/env python3

import sys,os
import signal
from os.path import dirname, join, pardir

try:
    from src import radiotray
except ImportError:
    from radiotray import radiotray
	
signal.signal(signal.SIGINT, signal.SIG_DFL)

radiotray.main(sys.argv[1:])
