#!/usr/bin/env python

import sys,os
from os.path import dirname, join, pardir

try:
	from radiotray import radiotray
except:
	basedir = os.path.dirname(os.path.realpath(__file__))
	workdir = join(basedir,'src')
	sys.path.insert(0, workdir)
	os.chdir(workdir)
	import radiotray 
	
radiotray.main()
